version: "3.9"

services:
  # 🌐 Frontend GESCOMPH - QA
  gescomph-front-qa:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../..               # raíz del proyecto Angular
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    restart: always
    ports:
      - "4201:${PORT}"             # 4201 host → 80 contenedor
    env_file:
      - .env
    networks:
      - gescomph_network           # 🔗 red compartida con backend
    labels:
      - com.gescomph.environment=qa

# 🔗 Red externa compartida con backend
networks:
  gescomph_network:
    external: true
